{
 "title": "VOO",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voo_up_total{system=\"voo.furest.be\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voo_up_total{system=\"voo.furest.be\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CM Mac Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voo_up_total{system=\"voo.furest.be\"}",
     "legendFormat": "{{mac_address}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voo_up_total{system=\"voo.furest.be\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Downstream Power (dBmV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "voo_downstream_channel_1_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH1"
    },
    {
     "expr": "voo_downstream_channel_2_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH2"
    },
    {
     "expr": "voo_downstream_channel_3_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH3"
    },
    {
     "expr": "voo_downstream_channel_4_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH4"
    },
    {
     "expr": "voo_downstream_channel_5_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH5"
    },
    {
     "expr": "voo_downstream_channel_6_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH6"
    },
    {
     "expr": "voo_downstream_channel_7_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH7"
    },
    {
     "expr": "voo_downstream_channel_8_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH8"
    },
    {
     "expr": "voo_downstream_channel_9_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH9"
    },
    {
     "expr": "voo_downstream_channel_10_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH10"
    },
    {
     "expr": "voo_downstream_channel_11_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH11"
    },
    {
     "expr": "voo_downstream_channel_12_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH12"
    },
    {
     "expr": "voo_downstream_channel_13_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH13"
    },
    {
     "expr": "voo_downstream_channel_14_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH14"
    },
    {
     "expr": "voo_downstream_channel_15_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH15"
    },
    {
     "expr": "voo_downstream_channel_16_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH16"
    }
   ]
  },
  {
   "title": "Downstream SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "voo_downstream_channel_1_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH1"
    },
    {
     "expr": "voo_downstream_channel_2_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH2"
    },
    {
     "expr": "voo_downstream_channel_3_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH3"
    },
    {
     "expr": "voo_downstream_channel_4_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH4"
    },
    {
     "expr": "voo_downstream_channel_5_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH5"
    },
    {
     "expr": "voo_downstream_channel_6_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH6"
    },
    {
     "expr": "voo_downstream_channel_7_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH7"
    },
    {
     "expr": "voo_downstream_channel_8_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH8"
    },
    {
     "expr": "voo_downstream_channel_9_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH9"
    },
    {
     "expr": "voo_downstream_channel_10_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH10"
    },
    {
     "expr": "voo_downstream_channel_11_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH11"
    },
    {
     "expr": "voo_downstream_channel_12_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH12"
    },
    {
     "expr": "voo_downstream_channel_13_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH13"
    },
    {
     "expr": "voo_downstream_channel_14_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH14"
    },
    {
     "expr": "voo_downstream_channel_15_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH15"
    },
    {
     "expr": "voo_downstream_channel_16_snr{system=\"voo.furest.be\"}",
     "legendFormat": "CH16"
    }
   ]
  },
  {
   "title": "Upstream Power (dBmV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "voo_upstream_channel_1_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH1"
    },
    {
     "expr": "voo_upstream_channel_2_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH2"
    },
    {
     "expr": "voo_upstream_channel_3_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH3"
    },
    {
     "expr": "voo_upstream_channel_4_power{system=\"voo.furest.be\"}",
     "legendFormat": "CH4"
    }
   ]
  }
 ]
}